/*
 * Copyright (c) 2015 XING AG (http://xing.com/)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.xing.android.sdk.model.user;

import com.xing.android.sdk.model.JsonEnum;

/**
 * Possible Industries.
 * <p/>
 * @author serj.lotutovici
 */
public enum Industry implements JsonEnum {
    ACADEMIA, ACCOUNTING, AEROSPACE, AGRICULTURE, AIRLINES, ALTERNATIVE_MEDICINE,
    APPAREL_AND_FASHION, ARCHITECTURE_AND_PLANNING, ARTS_AND_CRAFTS, AUTOMOTIVE, BANKING,
    BIOTECHNOLOGY, BROADCAST_MEDIA, BUILDING_MATERIALS, BUSINESS_SUPPLIES_AND_EQUIPMENT,
    CHEMICALS, CIVIC_AND_SOCIAL_ORGANIZATIONS, CIVIL_ENGINEERING, CIVIL_SERVICE, COMPOSITES,
    COMPUTER_AND_NETWORK_SECURITY, COMPUTER_GAMES, COMPUTER_HARDWARE, COMPUTER_NETWORKING,
    COMPUTER_SOFTWARE, CONSTRUCTION, CONSULTING, CONSUMER_ELECTRONICS, CONSUMER_GOODS,
    CONSUMER_SERVICES, COSMETICS, DAYCARE, DEFENSE_MILITARY, DESIGN, EDUCATION, ELEARNING,
    ELECTRICAL_ENGINEERING, ENERGY, ENTERTAINMENT, ENVIRONMENTAL_SERVICES, EVENTS_SERVICES,
    FACILITIES_SERVICES, FACILITY_MANAGEMENT, FINANCIAL_SERVICES, FISHERY, FOOD, FUNDRAISING,
    FURNITURE, GARDENING_LANDSCAPING, GEOLOGY, GLASS_AND_CERAMICS, GRAPHIC_DESIGN,
    HEALTH_AND_FITNESS, HOSPITALITY, HUMAN_RESOURCES, IMPORT_AND_EXPORT, INDUSTRIAL_AUTOMATION,
    INFORMATION_SERVICES, INFORMATION_TECHNOLOGY_AND_SERVICES, INSURANCE, INTERNATIONAL_AFFAIRS,
    INTERNATIONAL_TRADE_AND_DEVELOPMENT, INTERNET, INVESTMENT_BANKING, JOURNALISM,
    LEGAL_SERVICES, LEISURE_TRAVEL_AND_TOURISM, LIBRARIES, LOGISTICS_AND_SUPPLY_CHAIN,
    LUXURY_GOODS_AND_JEWELRY, MACHINERY, MANAGEMENT_CONSULTING, MARITIME,
    MARKETING_AND_ADVERTISING, MARKET_RESEARCH, MECHANICAL_INDUSTRIAL_ENGINEERING,
    MEDIA_PRODUCTION, MEDICAL_DEVICES, MEDICAL_SERVICES, MEDICINAL_PRODUCTS, METAL_METALWORKING,
    METROLOGY_CONTROL_ENGINEERING, MINING_AND_METALS, MOTION_PICTURES,
    MUSEUMS_AND_CULTURAL_INSTITUTIONS, MUSIC, NANOTECHNOLOGY, NON_PROFIT_ORGANIZATION,
    NURSING_AND_PERSONAL_CARE, OIL_AND_ENERGY, ONLINE_MEDIA, OTHERS, OUTSOURCING_OFFSHORING,
    PACKAGING_AND_CONTAINERS, PAPER_AND_FOREST_PRODUCTS, PHOTOGRAPHY, PLASTICS, POLITICS,
    PRINTING, PRINT_MEDIA, PROCESS_MANAGEMENT, PROFESSIONAL_TRAINING_AND_COACHING,
    PSYCHOLOGY_PSYCHOTHERAPY, PUBLIC_HEALTH, PUBLIC_RELATIONS_AND_COMMUNICATIONS, PUBLISHING,
    RAILROAD, REAL_ESTATE, RECREATIONAL_FACILITIES_AND_SERVICES, RECYCLING_AND_WASTE_MANAGEMENT,
    RENEWABLES_AND_ENVIRONMENT, RESEARCH, RESTAURANTS_AND_FOOD_SERVICE, RETAIL,
    SECURITY_AND_INVESTIGATIONS, SEMICONDUCTORS, SHIPBUILDING, SPORTS, STAFFING_AND_RECRUITING,
    TAX_ACCOUNTANCY_AUDITING, TELECOMMUNICATION, TEXTILES, THEATER_STAGE_CINEMA, TIMBER,
    TRAFFIC_ENGINEERING, TRANSLATION_AND_LOCALIZATION, TRANSPORT,
    VENTURE_CAPITAL_AND_PRIVATE_EQUITY, VETERINARY, WELFARE_AND_COMMUNITY_HEALTH, WHOLESALE,
    WINE_AND_SPIRITS, WRITING_AND_EDITING, PHARMACEUTICALS;

    @Override
    public String getJsonValue() {
        return name();
    }
}
